### ISSUE TITLE
feishu-openclaw-plugin failed after openclaw updated to 3.22

### ISSUE THREAD

**Issue by wuxiaojun514** [AlexAnys/openclaw-feishu#76]
I got Cannot find module 'openclaw/plugin-sdk' error when I upgraded openclaw to 3.22

<img width="1100" height="141" alt="Image" src="https://github.com/user-attachments/assets/a3b6c7c0-460f-4e5f-baa6-c47d3ee7b268" />

It seems that openclaw 3.22 has some break changes

https://zhuanlan.zhihu.com/p/2019670116128792830
